apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 1991199119911991sassd/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MSSQL_HOST
          value: "mssql-service.my-flask-app.svc.cluster.local"
        - name: MSSQL_PORT
          value: "1433"
        - name: MSSQL_DB
          value: "master"
        - name: MSSQL_USER
          valueFrom:
            secretKeyRef:
              name: mssql-secrets
              key: mssql-user
        - name: MSSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secrets
              key: mssql-password
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: secret-key
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"