apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: your-docker-registry/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: "host.docker.internal"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "domain_certificates"
        - name: POSTGRES_USER
          value: "devops"
        - name: POSTGRES_PASSWORD
          value: "devops"

