apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 1991199119911991sassd/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: "192.168.64.1"
        - name: POSTGRES_PORT
          value: "$(POSTGRES_SERVICE_SERVICE_PORT)"
        - name: POSTGRES_DB
          value: "domain_certificates"
        - name: POSTGRES_USER
          value: "devops"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: secret-key
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
