apiVersion: v1
kind: Secret
metadata:
  name: mssql-secrets
  namespace: my-flask-app
type: Opaque
data:
  mssql-user: c2E=              # base64 encoded 'sa'
  mssql-password: QGRtaW4xMjM=   # base64 encoded '@dmin123'