apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-flask-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: my-flask-app
spec:
  selector:
    app: flask-app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer

